### PR TITLE
Fix position of wide frames

### PR DESCRIPTION
**Pull request by kurnevsky**
It calculates wrong position if the buffer is still too wide after resizing.

### CODE REVIEW

**Comment by yyoncho** [comment]
Thank you, can you share how to test this PR?

**Comment by kurnevsky** [comment]
I noticed it on my project where I had a very long type written without spaces so it couldn't be wrapped on resizing phase. So you need to display a long string inside this buffer somehow.

**Comment by yyoncho** [comment]
Sorry, but I am not very familiar with that piece of code - is this fix for https://github.com/emacs-lsp/lsp-ui/issues/248 or it addresses only the placement?

**Comment by kurnevsky** [comment]
Here is the original issue:
screenshot-2019-07-31-20:18:46
How it looks after the fix:
screenshot-2019-07-31-20:26:18

Also I took courage to fix it for case when there is another buffer at the right:
screenshot-2019-07-31-20:26:33
After the fix:
screenshot-2019-07-31-20:26:51

**Comment by yyoncho** [comment]
I think that the second part of the change (moving the popup in the current window bounds instead of using current frame bounds) should be configurable because I guess that there are people preferring that location (e. g. when doing a vertical split space in the current window might not be sufficient). @sebastiencs what do you think?

**Comment by kurnevsky** [comment]
> when doing a vertical split space in the current window might not be sufficient

In this case it will be drawn over right window from the beginning of the frame. But ok, ping me if you want it configurable.

**Comment by kurnevsky** [comment]
Made it configurable.

**Pull request merged**
