### PR TITLE
Fix: #421 Revert "fix: Place cl-eval-when after provide"

### PR DESCRIPTION
**Pull request by MatthewZMD**
This reverts commit 5ba04fd9f37f808bb0abf848ea939e8a31d5b412.

Signed-off-by: Mingde (Matthew) Zeng <matthewzmd@gmail.com>

### CODE REVIEW

**Comment by brotzeit** [comment]
Doesn't work ?

**Comment by brotzeit** [comment]
You also have to revert the other part. Now the build complains about recursive require.

**Comment by brotzeit** [comment]
This seems to only affect `lsp-ui-doc-winum-ignore` right ?

**Comment by MatthewZMD** [comment]
> You also have to revert the other part. Now the build complains about recursive require.

Done

> This seems to only affect lsp-ui-doc-winum-ignore right ?

Yes, or I can simply move `(require 'lsp-ui-doc)` up.

**Comment by MatthewZMD** [comment]
```
FAILED  lsp-ui-test-sideline-overlays
```
hmmmm

**Comment by thanhvg** [comment]
Can this nested ater-load be ok?:
```` elisp
(with-eval-after-load 'winum
  (with-eval-after-load 'lsp-ui-doc
    (when (and (boundp 'winum-ignored-buffers-regexp) lsp-ui-doc-winum-ignore)
      (add-to-list 'winum-ignored-buffers-regexp lsp-ui-doc--buffer-prefix))))
````

**Comment by cireu** [comment]
Please revert commits from 5ba04fd..9b1b5ce, thanks a lot!

This hacky code trick rely on the behaviour of Emacs byte-compiler and  I forget many details about it,(That PR was created in the July of past year). So it may cause unpredictable behaviour if nobody understand how it works.

**Comment by MatthewZMD** [comment]
> Please revert commits from 5ba04fd..9b1b5ce, thanks a lot!

Done

> This hacky code trick rely on the behaviour of Emacs byte-compiler and I forget many details about it,(That PR was created in the July of past year). So it may have unpredictable behaviour if nobody understand how it works.

I'd say we revert this for now, as it's breaking on a lot of people's machine. If you remember the details again and decide to reimplement the feature, please submit another PR. Thanks!

**Pull request merged**
