### PR TITLE
[lsp-ui-doc] Add option to disable markdown formatting

### PR DESCRIPTION
**Pull request by sebastiencs**
Attempt to address #611

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]

**Review by jcs090218 — APPROVED** [review]

**Comment by anonimitoraf** [comment]
Hi guys, anything stopping this branch from being merged to master?

**Comment by jcs090218** [comment]
The code looks good to me! Does these changes resolved the issue for you?

**Comment by anonimitoraf** [comment]
image
Hmm I still see the overflow described in https://github.com/emacs-lsp/lsp-ui/issues/611

I did notice that this only happens when `lsp-ui-doc-use-childframe` is set to `t`. If set to `nil` it seems fine (but other problems: can't scroll down)
image

**Comment by ericdallo** [comment]
Merging this as it seems to improve current behavior

**Pull request merged**
