### PR TITLE
change default value of lsp-ui-doc-position to at-point

### PR DESCRIPTION
**Pull request by brotzeit**
I think most users prefer this position. But maybe I'm wrong...

### CODE REVIEW

**Comment by jcs090218** [comment]
I personally use at-point. No strong objection here.

**Review by ericdallo — APPROVED** [review]

**Review by jcs090218 — APPROVED** [review]

**Comment by yyoncho** [comment]
This was recently changed by @sebastiencs  to try to avoid lsp-ui doc hiding the text near cursor.

**Comment by sebastiencs** [comment]
@brotzeit @jcs090218 The new default has been discussed here: https://github.com/emacs-lsp/lsp-ui/pull/493#issuecomment-684919990

The `at-point` behavior is now reproduced with the mouse pointer: see this comment: https://github.com/emacs-lsp/lsp-ui/issues/508#issuecomment-692239567

The new default is to avoid hiding part of the buffer around the cursor.
This is to follow this issue: https://github.com/emacs-lsp/lsp-ui/issues/494

**Comment by jcs090218** [comment]
> The new default has been discussed here: #493 (comment)

I see. Thanks for updating me this!

**Pull request merged**
