### PR TITLE
[lsp-ui-sideline] Reduce calls to line-number-at-pos

### PR DESCRIPTION
**Pull request by sebastiencs**
`line-number-at-pos` is the slowest operation in lsp-ui-sideline and was
called several times, including in post-command-hook.
It impacts performance only with big buffers.

This reduce the number of calls to this function to 0 or 1.
It is now called only after the timer `lsp-ui-sideline-delay`, and when the cursor changes of line.
When the cursor stays on the same line it doesn't call `line-number-at-pos`

@kurnevsky This should also fix the issue we mentioned in https://github.com/emacs-lsp/lsp-ui/pull/509
Can you please confirm ?

### CODE REVIEW

**Comment by kurnevsky** [comment]
Yes, it fixes that issue.

**Comment by kurnevsky** [comment]
Though I noticed one problem - if I move cursor quickly old requests are not cancelled and they start execute with new ones.

**Comment by kurnevsky** [comment]
I fixed it in this commit: https://github.com/emacs-lsp/lsp-ui/commit/4094eaf557ae43229abf3a0cf6e53c0a446f7bf0
But for some reason it was deleted :(

**Comment by sebastiencs** [comment]
> Though I noticed one problem - if I move cursor quickly old requests are not cancelled and they start to execute with new ones and redraw the same sideline multiple times.

Does this occurs on the master branch ?

> I fixed it in this commit: 4094eaf
But for some reason it was deleted :(

Ah, this has been removed for https://github.com/emacs-lsp/lsp-ui/issues/483

**Comment by kurnevsky** [comment]
> Does this occurs on the master branch ?

Yes.

**Comment by kurnevsky** [comment]
@sebastiansturm will you merge this? At least it doesn't make things worse :)

**Review by jcs090218 — APPROVED** [review]
I have tested and I think this should be good to merge! 💯 👍

**Pull request merged**
