### PR TITLE
Don't request hover when server cannot handle textDocument/hover

### PR DESCRIPTION
**Pull request by wyuenho**
Related: https://github.com/emacs-lsp/lsp-mode/pull/375

### CODE REVIEW

**Comment by gpittarelli** [comment]
I tested this with [groovy-language-server](https://github.com/palantir/language-servers) (which doesn't support hover) and it fixes an error :) Thanks

**Comment by MaskRay** [comment]
In this case `lsp-ui-doc-mode` isn't useful. Can you just make `lsp-ui-doc-enable` a no-op?

**Comment by wyuenho** [comment]
Following that logic, shouldn't all lsp-ui features be able to disable itself?

The way lsp-mode and lsp-ui are architected now, individual lsp-ui features know nothing about the server's state. They just naively register themselves to a bunch of standard emacs hooks, and attempt to make a request to a server, without regard whether it's up, initialized or ready.

Say I do disable lsp-ui-doc when textDocument/hover capability isn't found, the fact that capability isn't available doesn't tell me whether the server is being started, or initialized but not ready. So, when the server is started, initialized, and ready, I would have already disabled lsp-ui-doc, so what do I do now? Restart lsp-ui? The architecture and design in lsp-mode and lsp-ui is insane. If you are following a naive polling model, just stick with it instead of introducing yet another intermediate state that causes more trouble than it's worth. This is the simplest solution to solve the problem of "I'm suppose to get some documents from the server but I don't know anything about the server's state".

**Comment by wyuenho** [comment]
@MaskRay Ping

**Comment by MaskRay** [comment]
@wyuenho Sorry for taking so long to get to this. I am not good at elisp so not comfortable merging PRs even though I somehow get the permission. I was hoping to get more feedback from other more skilled people.

There seems a trend to make more stuff `*Provider`and the change is in line with recent lsp-mode changes so I'll merge this.

BTW, you might be interested at https://github.com/MaskRay/ccls/wiki/Getting-started but I'm very opinionated :)

**Pull request merged**
