### PR TITLE
Fix #615: Display the border color of the child frame.

### LINKED ISSUE #615: The border color is not displayed correctly
https://github.com/emacs-lsp/lsp-ui/blob/efae00eb6a733d5271cb33e9d92c3d8c2fa98dde/lsp-ui-doc.el#L838

I think `child-frame-border` should be set as well. I can submit a PR to fix if you'd like.

### PR DESCRIPTION
**Pull request by seagle0128**
Fix #615 .

See 
https://github.com/tumashu/posframe/blob/739d8fd1081bdd0d20dee9e437d64df58747b871/posframe.el#L355-L356.

### CODE REVIEW

**Review by ericdallo — APPROVED** [review]
I was facing the same issue, thanks!

**Comment by seagle0128** [comment]
The CI seems failed due to the env issue?

**Comment by jcs090218** [comment]
Thanks for the fix!

**Comment by CsBigDataHub** [comment]
@seagle0128 This PR works fine on Emacs 28, but it does not display border on Emacs 27. Is there a work around to get it working on Emacs27?

Thanks

**Comment by seagle0128** [comment]
@CsBigDataHub I think it's an issue of Emacs 27.

**Comment by CsBigDataHub** [comment]
@seagle0128 I think this a issue on MacOs builds, I can see borders on Ubuntu KellyK emacs 27.

**Comment by seagle0128** [comment]
Yes. It's an issue of Emacs 27 on macOS.

**Pull request merged**
