### PR TITLE
LSP UI changes needed to make signature support work on lsp-ui side

### LINKED ISSUE #204: lsp-ui-doc--extract oddity for "MarkedString[]"
`lsp-ui-doc--extract`, used to render the pop-up window for hover text, has the following fragment for processing the `MarkedString[]` case

```elisp
   ((sequencep contents) ;; MarkedString[]
    (mapconcat 'lsp-ui-doc--extract-marked-string
               (lsp-ui-doc--filter-marked-string contents)
               "\n\n"
               ;; (propertize "\n\n" 'face '(:height 0.4))
               ))
```
This calls `lsp-ui-doc--filter-marked-string` on `contents`.  It it not clear to me what  `lsp-ui-doc--filter-marked-string` is intended to do, but it does invoke an idle timer function.  The nett effect for me is that the hover window only sometimes shows up.

Changing this to
```elisp
   ((sequencep contents) ;; MarkedString[]
    (mapconcat 'lsp-ui-doc--extract-marked-string
               contents
               "\n\n"
               ;; (propertize "\n\n" 'face '(:height 0.4))
               ))
```
Results in reliable display of the hover (except the very first time for a file, which I assume is an initialization issue, separate from this, see #178 )

So, is there any reason to call  `lsp-ui-doc--filter-marked-string` ?  If so, should it be a different version, without the idle timer randomly inserted in the middle?

### PR DESCRIPTION
**Pull request by yyoncho**
Fixes #204

Requires: https://github.com/emacs-lsp/lsp-mode/pull/544

### CODE REVIEW

**Comment by alanz** [comment]
I just tried this version, the hover info shows up in the message area, but it is the raw markdown.

Is there a setting to get it to use the separate overlay window instead? as it used to

**Comment by yyoncho** [comment]
Can you post a screenshot? I will install the haskell server so I can try it out.

**Comment by alanz** [comment]
See

screenshot from 2018-12-16 18-39-43

Installing the haskell server is not for the faint of heart, but shout if you decide to do it and need help.

**Comment by yyoncho** [comment]
I had some problems with the haskell ide(I had it working only in setup.hs) but the docs that were there looked like this:
emacs myoncho_072

Did you include https://github.com/emacs-lsp/lsp-mode/pull/544 when testing?

**Comment by alanz** [comment]
nope, I brought in lsp-mode master. Will try again

**Comment by alanz** [comment]
I brought that in, it made no difference until I disabled my prefer-flymake customisation.

Then I got 
screenshot from 2018-12-16 21-00-41

I think I need to back off my config, and build it back slowly, to see what is clashing.

But that will have to be tomorrow only.

**Comment by yyoncho** [comment]
Ok, make sure that you have markdown-mode present since it is not a lsp.el dependency but without it you won't get markdown rendering.

**Pull request merged**
