### PR TITLE
lsp-ui-doc: send hover request only for supported servers

### PR DESCRIPTION
**Pull request by leungbk**
----

#

### CODE REVIEW

**Comment by sebastiencs** [comment]
@leungbk Thanks !

@yyoncho `lsp--capability` does not seem to be a function that return quickly, considering that `lsp-ui-doc--handle-mouse-movement` will be call on _every_ mouse movement.

Can the return value of `(lsp--capability :hoverProvider)` changed during the session ?
Or we can cache it in a variable.

**Comment by yyoncho** [comment]
> Can the return value of `(lsp--capability :hoverProvider)` changed during the session ?
> Or we can cache it in a variable.

It can if you have 2 servers connected to the buffer and kill one of them it might change. Not sure if we should be concerned about this case. 

BTW it is better to use `lsp-feature?` instead of `lsp--capability`. `lsp-feature?` can be optimized a lot as it is.

**Comment by yyoncho** [comment]
And one more case - I think that might lsp-ui will be initialized before the server has returned its capabilities.

**Comment by sebastiencs** [comment]
@yyoncho Right, thanks !

@leungbk Can you move that check to `lsp-ui-doc--mouse-display`.
`lsp-ui-doc--handle-mouse-movement` should remains as fast as possible.

**Comment by sebastiencs** [comment]
Thank you @leungbk

**Pull request merged**
