### PR TITLE
fixing

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by brotzeit** [comment]
@yyoncho Do you need help with maintaining this repo ?

**Comment by yyoncho** [comment]
> @yyoncho Do you need help with maintaining this repo ?

IMO ATM lsp-ui needs a primary maintainer since @MaskRay and @sebastiencs are no longer active.

**Comment by brotzeit** [comment]
Hmmm, that's too much for me. Maybe we should open an issue like for the lsp-mode repo. It worked pretty well ;)

**Comment by brotzeit** [comment]
@yyoncho Maybe I can help a little here. Can you give me write access ?

**Pull request merged**
